### ISSUE TITLE
The training time of "get unlearned model"

### ISSUE THREAD

**Issue by lucasliunju** [OPTML-Group/Unlearn-Simple#1]
Thank you for your great work. 

I find you use 8 gpus to train simnpo on TPFU. I would like to ask the training time for that process. For example, the training time with 8 A100 gpus. And then I can estimate the time with one A100 GPU. 

Thank you very much!

**Comment by a-F1** [comment]
Thank you for your interest and attention to our work. You can find the details of the runtime in Appendix C.2.

We recommend using the same number of GPUs to replicate the experimental results. We have found that due to the impact of acceleration frameworks such as DeepSpeed and FlashAttention, it is important to ensure that both the fine-tuning of the origin model and the unlearning use the same number of GPUs to maintain experimental fairness.

If you prefer to use a single A100 GPU for replication, we suggest fine-tuning the origin model on one A100 first, and then performing the unlearning on your origin model using one A100. Please note that β and γ will need to be slightly adjusted during the unlearning process to account for the change in the number of GPUs.

If you have any further questions, feel free to reach out to us.

**Comment by a-F1** [comment]
Thank you for sharing the results with us. Could you let us know how you obtained the origin model?

**Comment by a-F1** [comment]
I understand. If you prefer to use two A100 GPUs for replication, we suggest fine-tuning the original model on two A100 GPUs first, and then performing the unlearning on the original model using the same two GPUs.

We strongly recommend using the same number of GPUs as in the original experiment to replicate the results accurately, given the potential impact of acceleration frameworks such as DeepSpeed and FlashAttention.

**Comment by a-F1** [comment]
Thank you so much. Could you provide more details? For example, the versions of CUDA, DeepSpeed, and FlashAttention that you're using?

**Comment by a-F1** [comment]
That's quite strange, as we haven't made any modifications to the original NPO code. Here are the specific versions used in our environment. I noticed that the versions of CUDA, DeepSpeed, and FlashAttention are different.

**Comment by a-F1** [comment]
Thank you for your support and interest in our work. We have uploaded the relevant checkpoints, and we’d appreciate it if you could give them a try. 
In Figure 3, we present the relationship between SimNPO’s evaluation metrics and the unlearning steps.
